apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce-prod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:5001']
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:5002']
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:5003']
