apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SushmithaSudarshan/sre-ecommerce-platform
    targetRevision: main
    path: phase-4-gitops/kubernetes/prod
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true