apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sushmithasudarshan/product-service:d356a91d8d75ccc7c9af09df6e72ce60dc5fed8f
          ports:
            - containerPort: 5001
